config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :travels do
      resources :points, only: [:index,:new,:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :travel

end

app/models/travel.rb
class Travel < ApplicationRecord
  has_many :points, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :travels, foreign_key: :created_by
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?    
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_travel

  def index
    @travel.points
  end

  def create
    @travel.points.create!(point_params)
    @notDone = true
    redirect_to new_user_travel_url
  end

  private

  def point_params
    params.require(:points).permit(:latitude,:longitude)
  end

  def set_travel
    @travel = current_user.travels.find(params['travel_id'])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] =  user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password are invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
    before_action :set_travel, only: [:show, :update, :destroy]
    #before_action :authorize
  def index
    user = current_user
    @travels = user.travels
  end

  def new
    @last = Travel.last
    @travel = current_user.travels.build
  end

  def create
    @travel = current_user.travels.create!(travel_params)
    @id_travel = @travel.id
    @done = false
    redirect_to new_user_travel_url
  end

  def show
    @travel
  end

  def update
    @travel.update(travel_params)
    redirect_to new_user_travel_url
  end

  def destroy
    @travel.destroy
    redirect_to user_travels_path
  end

  private

  def set_travel
    @travel = Travel.find(params['id'])
  end

  def travel_params
    params.require(:travel).permit(:title,:done)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Successfully"
    else
      flash.now.alert = "Errors ocurred trying to register"
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>
  <body>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-info <%= key %>"><%= value %></div>
      <% end %>
      <% if current_user %>
      <br>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Find App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
             <%= link_to "Nuevo", new_user_travel_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Viajes", user_travels_path(current_user.id), class: "nav-link" %>
            </li>
          </ul>
          <span class="navbar-text">
              <%= current_user.name %>&nbsp;&nbsp;
              <%= link_to "Log Out", session_path("current"), method: "delete" %>
          </span>
        </div>
      </nav>
      <% else %>
      <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Sign Up", new_user_path %> &nbsp;&nbsp;</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Log In", new_session_path %></a>
      </li>
    </ul>
      <% end %>
      

    <%= yield %>
  </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

app/views/travels/index.html.erb
<h1>Travels by <%= current_user.name %></h1>

<% @travels.each do |travel| %>
 <% if travel.done %>
<div class="card">
  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
  <div class="card-body">
    <h5 class="card-title">  <%= travel.title %> </h5>
    <%= link_to 'Show', user_travel_url(current_user.id,travel.id), class: "btn btn-primary" %>
    <%= link_to 'Destroy', user_travel_url(current_user.id,travel.id), class: "btn btn-danger",
                    method: :delete, data: { confirm: 'Are you sure?' } %>
    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
  </div>
</div>
<div class="container">
</div>
<% end %>
<% end %>

app/views/travels/new.html.erb
<% if @last and @last.done %>
<%= form_for([current_user , @travel]) do |f|%>
<div class="form-group">
  <%= f.label :title %><br />
  <%= f.text_field :title , class: 'form-control', :required => true%>
</div>
<div class="field">
  <%= f.hidden_field :done, :value => false %>
</div>
<div class="actions">
  <%= f.submit "Start" , :class => 'btn btn-primary'%>
</div>
<% end %>
<%  elsif not @last %>
<%= form_for([current_user , @travel]) do |f|%>
<div class="form-group">
  <%= f.label :title %><br />
  <%= f.text_field :title , class: 'form-control', :required => true%>
</div>
<div class="field">
  <%= f.hidden_field :done, :value => false %>
</div>
<div class="actions">
  <%= f.submit "Start" , :class => 'btn btn-primary'%>
</div>
<% end %>
  <% else %>
  You are traveling to <%= @last.title %>
  <%= form_for :travel , method: :put, :url => {:action => "update", :id => @last } do |f| %>
  <div class="field">
    <%= f.hidden_field :done, :value => true %>
  </div>
  <div class="actions">
    <%= f.submit "Finish" , :class => 'btn btn-primary'%>
  </div>
  <% end %>
<% end %>

<% if current_user and ( (@last && @last.done == false) or @notDone ) %>
<script type="text/javascript">
function myMap() {
  // Try HTML5 geolocation.
  console.log("sending");
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      $.ajax({
        url: "http://localhost:3000/users/<%= current_user.id%>/travels/<%= @last.id %>/points",
        type: "POST",
        data: {points: {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude }},
          success: function(resp){
            location.reload();
            // this.send();
          }
        });
    });
  } else {
    // Browser doesn't support Geolocation
    alert("location is not suppported");
  }
}


</script>


<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyClM3z3tp5qrlHSEXfuyaKtFUhzMX7KYiM&callback=myMap"></script>
  <% end %>

app/views/travels/show.html.erb
<script>
 var url = "";
</script>
<div class="container">
  <h3>This is the way you followed when you went to <%= @travel.title %></h3>
</div>
<% @travel.points.each do |e| %>
  <script>
    url += "|<%=e.latitude%>,<%=e.longitude%>";
  </script>
<% end %>
<script >
$(document).ready(function(){
    $src = "https://maps.googleapis.com/maps/api/staticmap?zoom=13&size=600x600&maptype=hybrid&path=color:0x0000ff|weight:5";
    $src += url;
    $src += "&key=AIzaSyClM3z3tp5qrlHSEXfuyaKtFUhzMX7KYiM";
    $("img").attr("src", $src);
});
</script>
<!-- path=color:0x0000ff|weight:5|40.737102,-73.990318|40.749825,-73.987963|40.752946,-73.987384|40.755823,-73.986397 -->
<div class="container">
  <img id="url" ></img>
</div>
<!-- https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=AIzaSyDwPHhFoPYRvAhLmHRQxJ42Tv6A5LM72vs -->

app/views/users/new.html.erb
<div class="container">

<h1> Sign up </h1>
<% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
<% end %>

<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control',:required => true %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: 'form-control',:required => true %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password,class: 'form-control', :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class: 'form-control',:required => true %>
  </div>
  <div class="actions">
    <%= f.submit 'Register', :class => 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/welcome/index.html.erb
<% unless current_user %>
<div class="container">
  You are watching your current position
</div>
<br>
<% end %>
<div class="container">

  <div class="jumbotron">
    <div id="map" style="width:100%;height:600px;"></div>

  </div>
</div>
<script>
  function myMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat:  6.217, lng: -75.567},
      zoom: 18,
    });
    var infoWindow = new google.maps.InfoWindow({map: map});
    // Try HTML5 geolocation.
    if (navigator.geolocation) {
      console.log("YESS");
      navigator.geolocation.getCurrentPosition(function(position) {
        console.log("VER");
        var pos = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        console.log("NEA")
        infoWindow.setPosition(pos);
        infoWindow.setContent('You are here');
        map.setCenter(pos);
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
  }

  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
                          'Error: The Geolocation service failed.' :
                          'Error: Your browser doesn\'t support geolocation.');
  }
</script>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyClM3z3tp5qrlHSEXfuyaKtFUhzMX7KYiM&callback=myMap"></script>
<!--
To use this code on your website, get a free API key from Google.
Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
-->
<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwPHhFoPYRvAhLmHRQxJ42Tv6A5LM72vs"></script> -->